### ISSUE TITLE
api.ai integration

### ISSUE THREAD

**Issue by Chaslav** [krilor/wp-chatbot#1]
Hi Kristoffer,

How is it going with this plugin? I see that you made a lot of stuff. I need to make a Wordpress livechat plugin that would connect with my chatbot built on api.ai

Is it possible to use your wp-chatbot for that?

**Comment by krilor** [comment]
Hi Chaslav

The plugin is coming along slowly. I plan on putting in some work this
weekend to get a minimum viable solution ready. I would love for you to
test it :)

I think it would definately be possible to connect to api.ai using this
plugin, but it would of course depend on what you actually want it to do.

Could you be a bit more specific on your need and maybe point to some docs
that describes the endpoint at api.ai that you would use? I would like to
see you use my plugin!

Best regards
Kristoffer

**Comment by Chaslav** [comment]
Hi Kristoffer,

Thanks for answering, it is good to hear that you think it is possible. Maybe I can help you over the weekend, and then test it. Send me an email, it will be easier to communicate milancheee@gmail.com

I think of a usual chat button in lower right corner, that when you click, you can start chatting, only instead of building a panel to see questions and send answer from there, connect it to api.ai and get instant answers. You can see how it looks on api.ai page for one bot I am making, you can send a message and you should get an instant answer https://bot.api.ai/16fd7efb-dc12-4073-bd8d-13f5dc42761c

As for documents, I guess this collection of SDKs can help https://docs.api.ai/docs/sdks
And this part for authentification https://docs.api.ai/docs/authentication

I also made a chatbot for a regular HTML website, so I will show you that as well..

Regards,
Milan

**Comment by krilor** [comment]
Hi again

I've now merged a MVS into the master branch, and it is ready for use/test.It includes a readme. If you find any issues, please just raise a new ticket. Same goes for enhancements and wishes.

These are the settings I've used for api.ai integration.

![apiai](https://cloud.githubusercontent.com/assets/6005028/21953464/3f88e174-da38-11e6-91d7-26d399ee5564.PNG)

/Kristoffer
