### ISSUE TITLE
Get error when trying activate plugin

### ISSUE THREAD

**Issue by tonygil** [krilor/wp-chatbot#31]
Parse error: syntax error, unexpected 'require' (T_REQUIRE), expecting identifier (T_STRING) in /home/giltedge/public_html/wordpress/wp-content/plugins/wp-chatbot-master/classes/base/class-wp-chatbot-base.php on line 83

**Comment by krilor** [comment]
Hi Tony

Thank you for creating the issue. For some odd reason, my dev environment does not throw that error. Anyways, I was able to reproduce it using a php code checker, and I have successfully fixed the issue and merged it into master.

Can you please try again and let me know about the outcome?

And btw - Please don't judge the plugin based on its current state, as it is still in development and pending initial release.  Currently the frontend is getting a facelift (fix) in the following development branch:

https://github.com/krilor/wp-chatbot/tree/clean-frontend

If you find some time to test the plugin, don't hesitate to ask me for help or give me feedback. I would love to connect with potential users to get input on how this plugin should work and what I should focus on going forward.

Thanks
Kristoffer

**Comment by tonygil** [comment]
Hi Kristoffer
That fix did activate to plugin without error. So i will have a look at the
plugin and feedback to you.

I have been looking at various chatbot builder, Motion.AI,Wit.Ai, Api.ai
The aim is to provide an AI bot which assists the user to find information
of our website. via conversational  search dialogue.

Thanks for your fast response.
Just trying to look at the setting tab now and figure what i need to do.

Thanks
Tony
