### ISSUE TITLE
Can you please guide me how to setup API.AI 

### ISSUE THREAD

**Issue by akhilgopinath** [krilor/wp-chatbot#34]
I am trying to install API.AI chat bot , 
How many params i should set ? only accessToken in request header ?
i used request url as https://api.api.ai/v1/query  

can you please guide me how to set up this

**Comment by krilor** [comment]
Hi Akhil

I can understand that the settings might be a bit cryptic. Working on that...

For api.ai integration, check out the screenshot in issue #1 . I think you can basically copy those settings, but you need to include you own client access token in the header. Leave "Bearer " as is but then add your [client access token](https://docs.api.ai/docs/authentication).

If you look at the settings, you can see that it kind of mathes the sample get in the [api.ai query docs](https://docs.api.ai/docs/query).

Let me know how it goes. Lets make it work!

**Comment by akhilgopinath** [comment]
thanks @krilor i tried same and its working now , thank you so much for your help 
i working on chatbot like this can i contribute something on UI ?,  i am trying to beautify the chatbot

**Comment by krilor** [comment]
No worries. I'm glad it works! I am currently working on cleaning ut the front end and trying to make it configurable in #8 , and I've put it in a separate branch [clean-frontend](https://github.com/krilor/wp-chatbot/tree/clean-frontend)

Once I have done the initial work, and merged it in, I would love to get som help on making it even nicer :) I'll let you know once it is merged.
