### ISSUE TITLE
What window scroll stops after 10-15 messages. Will not scroll to bottom.

### ISSUE THREAD

**Issue by krilor** [krilor/wp-chatbot#38]

**Comment by Maniae** [comment]
Hi,
I faced the issue, and dealt with it by replacing this line:
`jQuery('.chatbot-wrapper .chatbot-inner').scrollTop(jQuery('#wp-chatbot-content').height());`
with 
`jQuery('.chatbot-wrapper .chatbot-inner').scrollTop(jQuery('#wp-chatbot-content').prop("scrollHeight"));`
in js/wp-chatbot-pub.js (line 99, function scrollBottom())

**Comment by krilor** [comment]
Thanks Maniae. That solves the issue :)
