### ISSUE TITLE
Settings form wont save 

### ISSUE THREAD

**Issue by Maniae** [krilor/wp-chatbot#40]
When editing option in Settings --> WP Chatbot, my informations aren't saved after clicking the appropriate button and are field are blank upon refreshing (for both general and integration tabs). Thus I can't use the widget.
Using wordpress **4.4.10**.
Didn't have the problem on a local 4.7.5 wordpress version (but I can't update the production one for other reasons).

**Comment by krilor** [comment]
Hi Tom

I really don't know why this is happening. Do you have issues with any other plugins/settings pages behaving in the same way?

Anyways, I'm not able to try to reproduce this today, but I might be able to over the weekend. Please let me know if you can isolate what is causing the issue (plugin, wordpress version, PHP version.. ++ ) or if you have any more information that I can use to figure out what is the issue.

If you can, please give as much information as possible. Maybe some info using: https://wordpress.org/plugins/debug-info/

If you find any errors in browser console (unlikely?) or php logs (more likely?), please share.

**Comment by Maniae** [comment]
Hi,
Could this be an issue related to the php version ? Here are some more informations from debug-info: 
WordPress Version: 4.4.10
PHP Version: 5.5.9-1ubuntu4.11
MySQL Version: 5.5.44-0ubuntu0.14.04.1
Apache Version: This information is not available.

Noticed that when I press the "save modifications" button, I actually see the "settings saved" feedback message, but the modifications aren't really saved (the chat wont appear on the website and the settings form will be blank if I go back in it).
Nothing is print in the js console and no php log are shown with the WP_DEBUG mode enabled.

**Comment by VMArchisage** [comment]
Hi.  I am having the exact same issue as well.  I've got the same behaviour that it comes back saying Settings Saved, but the settings form is still blank.  My debug info is as follows:

WordPress Version: 4.6
PHP Version: 5.6.30
MySQL Version: 5.6.35
Apache Version: This information is not available.

Is there another way to store these values - like editting a php file or something?

**Comment by Maniae** [comment]
Hi,
I tried to use the plugin on a fresh new Wordpress running on 4.4.10 and reproduced the issue.

WordPress Version: 4.4.10
PHP Version: 7.0.15
MySQL Version: 5.6.35

Seems to be an issue related to the wordpress version, updating from 4.4.10 to 4.7.5 fixes the issue.

**Comment by krilor** [comment]
Thanks for all the input!

It seems that something has happened in WP 4.6-4.7. I'll have to dig into this some more. I haven't had the time to reproduce - but hopefully will soon :)

This might have something to do with the 4.7 change in [register_setting()](https://developer.wordpress.org/reference/functions/register_setting/). Note to self: Typo in sanetize vs sanitize migth cause issue.

**Comment by krilor** [comment]
Hey guys
I've been able to reproduce and fix the issue. It seems that it is in fact related to the 4.7 change in register_setting(). I reverted back to the old version, and now it works. Could you please test?
